const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

function readText(filePath) {
  return fs.readFileSync(filePath, 'utf8').replace(/^\uFEFF/, '');
}

function readJson(filePath) {
  return JSON.parse(readText(filePath));
}

function writeJson(filePath, value) {
  const body = `${JSON.stringify(value, null, 2)}\n`;
  fs.writeFileSync(filePath, body, 'utf8');
}

function slugify(value) {
  return String(value || '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function normalizeTitle(value) {
  return slugify(value).replace(/-/g, '');
}

function normalizePrompt(value) {
  return String(value || '')
    .replace(/\r\n?/g, '\n')
    .replace(/[ \t]+/g, ' ')
    .replace(/ *\n */g, '\n')
    .trim();
}

function promptHash(value) {
  return crypto.createHash('sha256').update(normalizePrompt(value)).digest('hex');
}

function escapeRegExp(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function extractMeta(markdown, name) {
  const pattern = new RegExp(`^(?:>\\s*)?\\*\\*${escapeRegExp(name)}:\\*\\*\\s*(.+?)\\s*$`, 'im');
  const match = String(markdown || '').match(pattern);
  return match ? match[1].trim() : '';
}

function extractPromptBlocks(section) {
  return Array.from(String(section || '').matchAll(/```(?:text|markdown|md)?\s*\n([\s\S]*?)\n```/gi))
    .map((match) => match[1].trim())
    .filter(Boolean)
    .sort((left, right) => right.length - left.length);
}

function extractMarkdownPrompt(markdown, filename) {
  const source = String(markdown || '').replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n');
  const titleMatch = source.match(/^#\s+(.+)$/m);
  const promptHeading = source.search(/^##\s+.*Prompt.*$/im);
  const promptSection = promptHeading >= 0 ? source.slice(promptHeading) : source;
  const promptBlocks = extractPromptBlocks(promptSection);
  let promptText = promptBlocks[0] || '';

  if (!promptText && promptHeading >= 0) {
    promptText = promptSection
      .replace(/^##\s+.*Prompt.*$/im, '')
      .replace(/\n---[\s\S]*$/, '')
      .replace(/\n\*Generated by[\s\S]*$/i, '')
      .trim();
  }

  return {
    id: extractMeta(source, 'ID'),
    title: titleMatch ? titleMatch[1].trim() : String(filename || '').replace(/\.md$/i, '').replace(/[_-]+/g, ' ').trim(),
    category: extractMeta(source, 'Category'),
    type: extractMeta(source, 'Type'),
    license: extractMeta(source, 'License'),
    promptText,
  };
}

const PLACEHOLDER_PATTERNS = [
  /prompt available on the source page/i,
  /full prompt (?:body )?is paywalled/i,
  /not yet in this catalog/i,
  /source page has not published the body/i,
];

function isCompletePrompt(value, record) {
  const prompt = normalizePrompt(value);
  const sourceKind = record && typeof record === 'object' ? record.source_kind : null;
  const minLength = sourceKind === 'community' ? 100 : 200;
  if (prompt.length < minLength) {
    return false;
  }
  return !PLACEHOLDER_PATTERNS.some((pattern) => pattern.test(prompt));
}

function sortCatalog(list) {
  return list.slice().sort((a, b) => {
    const ap = a && a.local_rel ? 1 : 0;
    const bp = b && b.local_rel ? 1 : 0;
    if (ap !== bp) return bp - ap;
    const ao = a && typeof a.sort_order === 'number' ? a.sort_order : Number.POSITIVE_INFINITY;
    const bo = b && typeof b.sort_order === 'number' ? b.sort_order : Number.POSITIVE_INFINITY;
    if (ao !== bo) return ao - bo;
    const ai = (a && a.id) || '';
    const bi = (b && b.id) || '';
    return ai < bi ? -1 : ai > bi ? 1 : 0;
  });
}

function detectAssetKind(absolutePath) {
  if (!absolutePath || !fs.existsSync(absolutePath)) {
    return 'other';
  }
  const extension = path.extname(absolutePath).toLowerCase();
  if (extension === '.mp4') return 'mp4';
  if (extension === '.m3u8') return 'hls';
  if (extension === '.webp') return 'webp';
  if (extension === '.gif') return 'gif';
  if (extension === '.png') return 'png';
  if (extension === '.jpg' || extension === '.jpeg') return 'jpeg';
  return 'other';
}

function auditCatalog({ root, merged, prompts, sources }) {
  const errors = [];
  const seenIds = new Set();
  const promptMap = new Map();
  const sourceIds = new Set((sources || []).map((record) => record.id));

  for (const record of prompts || []) {
    promptMap.set(record.id, record);
  }

  for (const record of merged || []) {
    if (seenIds.has(record.id)) {
      errors.push({ code: 'duplicate-id', id: record.id });
    } else {
      seenIds.add(record.id);
    }

    if (record.local_rel) {
      const absolutePath = path.join(root || process.cwd(), record.local_rel);
      if (!fs.existsSync(absolutePath)) {
        errors.push({ code: 'missing-asset', id: record.id, path: record.local_rel });
      }
    }

    if (record.source_kind === 'community' && record.source_id && !sourceIds.has(record.source_id)) {
      errors.push({ code: 'missing-source', id: record.id, path: record.source_id });
    }
  }

  for (const record of prompts || []) {
    const meta = (merged || []).find((item) => item.id === record.id) || record;
    if (!isCompletePrompt(record.prompt_text || '', meta)) {
      errors.push({ code: 'short-prompt', id: record.id });
    }
  }

  return { errors };
}

module.exports = {
  auditCatalog,
  detectAssetKind,
  extractMarkdownPrompt,
  isCompletePrompt,
  normalizePrompt,
  normalizeTitle,
  promptHash,
  readJson,
  slugify,
  sortCatalog,
  writeJson,
};
